### ISSUE TITLE
[explore-1] Warning: Invalid frame ID "x" passed to canTransform argument target_frame - frame does not exist

### ISSUE THREAD

**Issue by Richard-Haes-Ellis** [robo-friends/m-explore-ros2#11]
For some reason its throwing this waring constantly after launch, my frame "x" does exist as I can produce the tf tree and it shows up. 
What could cause this? 

Another inquiry is the params.yaml file, what exactly do you pass to the costmap topic? On the examples you put: map. As I undestrand map in it self is not a topic, /map is. And /map refrers to a normal map not a costmap. 

If you need more info I can gladly forward it.

**Comment by charlielito** [comment]
> For some reason its throwing this waring constantly after launch, my frame "x" does exist as I can produce the tf tree and it shows up. What could cause this?

Can you give more info? Your params file, what packages are you using, the tf tree, etc.

> Another inquiry is the params.yaml file, what exactly do you pass to the costmap topic? On the examples you put: map. As I undestrand map in it self is not a topic, /map is. And /map refrers to a normal map not a costmap.

`map` is a topic with the default namespace being `/` so at the end the topic will be `/map`. As in ROS1, this is done this way so you can prepend any namespace to the node in case you have multiple robots in the same network. Typically the maps are of type `nav_msgs::msg::OccupancyGrid` as well as costmaps. So you can use that for the exploration or the costmap topic of the navigation stack.

**Comment by charlielito** [comment]
Closing this since the author didn't respond. If in the furute he does I'll re open it
