### ISSUE TITLE
Package name does not match directory name

### ISSUE THREAD

**Issue by Timple** [robo-friends/m-explore-ros2#2]
Option 1: rename the `explore` directory to `explore_lite`.

Option 2: Move the complete package to the git root directory. Then rename this directory and package to `explore_lite` or `ros2_explore_lite`.

**Comment by charlielito** [comment]
It makes sense, but it is the way it is to keep things as close to the original ros1 version

**Comment by charlielito** [comment]
Closing this as we will keep the names to match the ros1 version
