### ISSUE TITLE
compile error at Humble ros2

### ISSUE THREAD

**Issue by ChanhoPark0208** [robo-friends/m-explore-ros2#25]
I got the following compile error at humble

m-explore-ros2-main/map_merge/include/combine_grids/grid_compositor.h:41:10: fatal error: nav_msgs/msg/occupancy_grid.hpp: No such file or directory
   41 | #include <nav_msgs/msg/occupancy_grid.hpp>

So, I added the following at CMakeLists.txt line102  and then fixed it.

#-----> added the following at line 102
ament_target_dependencies(combine_grids ${DEPENDENCIES})

Please, Could you fix this?

**Comment by charlielito** [comment]
Ah PR would be appreciated
