### ISSUE TITLE
Start / Stop exploring

### ISSUE THREAD

**Issue by Timple** [robo-friends/m-explore-ros2#7]
It would be nice if we can start and stop the exploring. Or maybe start until 'done'?

Would you accept a PR adding an action to start stop the exploration? Default can be started to keep backwards compatibility?

**Comment by charlielito** [comment]
Sure! PR's are welcome! I was also thinking adding the option to return to initial point after exploration is done

**Comment by Timple** [comment]
Ah yes, that would make a nice option.

Is there already a criterium when exploring is done?

**Comment by charlielito** [comment]
Yeah, it is donde when the algorithm cannot fins any new frontier https://github.com/robo-friends/m-explore-ros2/blob/main/explore/src/explore.cpp#L195 or it already visited all frontiers so far https://github.com/robo-friends/m-explore-ros2/blob/main/explore/src/explore.cpp#L211

**Comment by Timple** [comment]
Awesome!
